### ISSUE TITLE
My World When using this is a void map?[BUG]

### ISSUE THREAD

**Issue by OldGamedash43** [28Pollux28/ImageWorldGenerator#24] opened 2021-08-27 21:06 UTC
**Describe the bug**
When I press image generator preset with the image config and everything right its a void map.

**To Reproduce**
1. Follow the instructions
2. Void map

**Expected behavior**
My image to turn into a [world](url)

**Screenshots**
![satisfactorymapmc](https://user-images.githubusercontent.com/78713426/131188621-3e88fc59-02b2-43e4-9d4f-6638b859b2a9.png)

**Version**
Mod Version : 1.17+-+ImageWorldGenerator-1.3.3
Fabric Version : 0.11.6

Environment : Client

**Comment by 28Pollux28** [comment] 2021-08-27 21:12
Hi, this is a known issue when the png is using palette mode. It'll be fixed in 2.0. Try exporting the file from your image editor with a different profile (I use RGB or RGBA), let me know how it goes.

**Comment by OldGamedash43** [comment] 2021-08-27 21:31
I don’t have that option on my image program so I used a website and it didn’t work it’s still a void map.

**Comment by 28Pollux28** [comment] 2021-08-27 21:36
I have converted your image, it should work now.
Another option is to use sRVB color space in your image editor.
![hhhh](https://user-images.githubusercontent.com/40760287/131190958-36f8c6be-4cfe-49f0-972b-3182810a2ee6.png)

**Comment by OldGamedash43** [comment] 2021-08-27 21:48
Thank you so much! Do I have to worry about this when making the height map too?

**Comment by 28Pollux28** [comment] 2021-08-27 21:51
the problem is that those paletted png files are considered to be only 1 channel rgb resulting to be treated as a grayscale image. The heightmap won't be affected by this (in fact it will but since it is a grayscale there won't be a problem).

**Comment by 28Pollux28** [comment] 2021-08-27 21:51
The structure Map in the other hand will be affected

**Closed as completed by 28Pollux28** 2021-08-27 21:51 UTC
Labels: bug
